// Not sorted Icons
export { Add, AddCircleFilled } from "./add"
export { default as Airplane } from "./airplane"
export { default as ArrowDown } from "./arrow-down"
export { default as ArrowRightRound } from "./arrow-right-round"
export { default as ArrowRightSmallRound } from "./arrow-right-small-round"
export { default as Auth } from "./auth"
export { default as Calendar } from "./calendar"
export { default as Cancel } from "./cancel"
export { default as CancelCircle } from "./cancel-circle"
export { default as Cart } from "./cart"
export { CertificateFilled, CertificateOutlined } from "./certificate"
export { default as Check } from "./check"
export { default as ChevronDown } from "./chevron-down"
export { default as ChevronUp } from "./chevron-up"
export { ClockFilled, ClockOutlined } from "./clock"
export { ContainerTruckFilled } from "./container-truck"
export { CopyFilled, CopyOutlined } from "./copy"
export { default as CreditCard } from "./credit-card"
export { default as DeliveryTruck } from "./delivery-truck"
export { default as Email } from "./email"
export { default as EmailCode } from "./email-code"
export { Favorite } from "./favorite"
export { InvoiceFilled, InvoiceOutlined } from "./invoice"
export { default as MinusSign } from "./minus-sign"
export { default as Mobile } from "./mobile"
export { default as NowPayments } from "./now-payments"
export { default as Password } from "./password"
export { default as PencilEdit } from "./pencil-edit"
export { default as PlusSign } from "./plus-sign"
export { default as Search } from "./search"
export { default as Support } from "./support"
export { default as Tick } from "./tick"
export { default as Timer } from "./timer"
export { default as User } from "./user"
export { WalletFilled, WalletOutlined } from "./wallet"
export { default as Logout } from "./logout"
export { default as Flag } from "./flag"
export { default as Gift } from "./gift"
export { default as Task } from "./task"
export { default as UserEdit } from "./user-edit"
export { default as Partnership } from "./partnership"
export { default as DollarCircle } from "./dollar-circle"
export { default as OfficeWhiteBlack } from "./office-white-black"
export { default as Personal } from "./personal"
export { default as License } from "./license"
export { default as Fans } from "./fans"
export { default as Comfortable } from "./comfortable"

// Social Media Icons
export { default as Facebook } from "./(social-links)/facebook"
export { default as Google } from "./(social-links)/google"
export { default as Instagram } from "./(social-links)/instagram"
export { default as Telegram } from "./(social-links)/telegram"
export { default as X } from "./(social-links)/x"
export { default as TikTok } from "./(social-links)/tiktok"

// Mobile Store Icons
export { default as AppStore } from "./(mobile-store)/app-store"
export { default as GooglePlay } from "./(mobile-store)/google-play"

// Nagivation Icons
export { default as ArrowLeft } from "./(navigation)/arrow-left"
export { default as ArrowPaginationLeft } from "./(navigation)/arrow-pagination-left"
export { default as ArrowPaginationRight } from "./(navigation)/arrow-pagination-right"
export { default as ArrowRight } from "./(navigation)/arrow-right"
export { default as ArrowSelect } from "./(navigation)/arrow-select"
export { default as LinkCircle } from "./(navigation)/link-circle"

// Tags Icons
export { default as NFT } from "./(tags)/nft"
export { default as Quality } from "./(tags)/quality"
export { default as Signature } from "./(tags)/signature"
export { default as Soccer } from "./(tags)/soccer"

// Sport Icons
export { Football } from "./(sport)/football"
